version: '3.8'
services:
  reverse-tor:
    container_name: reverse-tor
    build: .
    image: reverse-tor:latest
    restart: always
    environment:
      REVERSE_PROXY: "nginx-test:80"
    volumes:
      - ./web:/web
    networks:
      - tor-public

  nginx-test:
    container_name: nginx-test
    image: nginx:latest
    restart: always
    networks:
      - tor-public

networks:
  tor-public:
    external: true
