services:
  reverse-tor:
    container_name: tor-reverse
    build:
      context: .
    image: ghcr.io/sudo88com/tor-reverse:latest
    restart: always
    environment:
      REVERSE_PROXY: "nginx-test:80"
    volumes:
      - ./web:/web

  nginx-test:
    container_name: tor-nginx
    image: nginx:latest
    restart: always
